linters-settings:
  gocyclo:
    min-complexity: 25
  govet:
    check-shadowing: false
  misspell:
    locale: "US_CA"

linters:
  enable-all: true
  disable:
    - gofumpt
    - golint
    - nosnakecase
    - varcheck
    - deadcode
    - structcheck
    - ifshort
    - interfacer
    - testpackage
    - gochecknoglobals
    - maligned
    - godox
    - nlreturn
    - exhaustivestruct
    - gochecknoinits
    - gocritic
    - scopelint
    - varnamelen
    - gofmt # TODO(XXX): remove once built with Go 1.19
