before:
  hooks:
    - go mod tidy

builds:
- id: dumpdb_linux
  binary: dumpdb
  env:
    - CGO_ENABLED=1
  goos:
    - linux
  goarch:
    - amd64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"
