schema = 3

[mod]
  [mod."github.com/alecthomas/participle"]
    version = "v0.7.1"
    hash = "sha256-1+HQl7F3CK03Y3GvxmgzXELCfI6+2+thhgov1LXouOo="
  [mod."github.com/alecthomas/participle/v2"]
    version = "v2.0.0-alpha7"
    hash = "sha256-Iy3/FxQ9kb0rp7N7olD/FuMNEja3OtPce61uGKjWReE="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.9"
    hash = "sha256-T4/79NKqmn7+nfa8HpfLB6nSBhlhY85Pcj5aYxK0RFo="
