schema = 3

[mod]
  [mod."github.com/alecthomas/participle/v2"]
    version = "v2.0.0-alpha7"
    hash = "sha256-Iy3/FxQ9kb0rp7N7olD/FuMNEja3OtPce61uGKjWReE="
  [mod."github.com/alecthomas/repr"]
    version = "v0.0.0-20181024024818-d37bc2a10ba1"
    hash = "sha256-fetD8YZGhIVdBiX1yUPprOQp1SnoC91AAPET2q4P3Uo="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.9"
    hash = "sha256-T4/79NKqmn7+nfa8HpfLB6nSBhlhY85Pcj5aYxK0RFo="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.0"
    hash = "sha256-az0Vd4MG3JXfaYbj0Q6AOmNkrXgmXDeQm8+BBiDXmdA="
  [mod."github.com/stretchr/testify"]
    version = "v1.4.0"
    hash = "sha256-yJw5uyO9WCd1/fxFK/1fYch8WKKALoqVFENX8Nt92fY="
  [mod."gopkg.in/check.v1"]
    version = "v0.0.0-20161208181325-20d25e280405"
    hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.2"
    hash = "sha256-SjNLmGSxoYabOi/zdjymW3mSgaxaS39btBQ3/aUIkgc="
