# Tests that the code builds without Nix.
name: Vanilla Go
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Vanilla Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19

    - name: Build
      run: go build -v ./...
